TheSpaghettiDetective/obico-server

- .circleci/config.yml
It's pretty common to have the latest tag rolling with the newest image, this change updates the circle ci process to tag it's current build as latest.
> When building an image with circle ci tag that image as the latest image

- docker-compose-dev.yml
- docker-compose.yml
- ml_api/Dockerfile
- web/Dockerfile
fixes #42
* ml_api now uses 9.0-runtime-ubuntu16.04 insead of 9.0-devel-ubuntu16.04
* ml_api no longer installs recommended packages (which are not requirements) and explicitly add a few packages because of this
* web now is based off of alpine
* combined a few run statements to reduce the layer count
* rearranged statements so things that don't change often (like requirements.txt or the model weights) are cached on rebuilds
* redis is now using the 5.0-alpine image
I've done some basic testing validating that the user interface seems to work as well as spaghetti detection by adding some to my print bed mid print manually, however I would not call the testing exhaustive, if there are any sort of regression tests I can run thru this I'd love to know so I could feel more confident about …
> Reduce docker image sizes and update docker compose to handle alpine images

- web/app/notifications.py
- web/app/templates/layout.html
The current SMS Notification uses a hardcoded URL instead of the configured URL. This just replaces the hard-coded URL with the generated one.
The Home button is hardcoded for the home page of the main site which is already accessible by clicking the logo to the left of Home. This just navigates to / when clicking Home for easier navigation.
> SMS Notification and Home button

- web/app/templates/account/email/email_confirmation_message.html
- web/app/templates/account/email/email_confirmation_signup_message.html
This is just a copy of the text email with a bit of HTML markup mostly to unblock users.  This can be made pretty later, given users only see it once (usually) it's low priority.  I did verify that if a client is set to not show HTML emails it does still work and they just see the text version.
> Create a basic HTML template for confirmation emails

- docker-compose.yml
- docs/jetson_guide.md
Use docker-compose.override.yml for Nvidia Jetson specific configuration. Includes web to be rebuilt using the web dockerfile.base as thespaghettidetective/web does not have an ARM64 image.
> Use Docker Compose Overide file for Jetson Settings

- web/app/templates/layout.html
RawGit is shutting down very soon,
jsDelivr will host the gauge javascript files.
> Replace RawGit Gauge CDN with jsDelivr CDN

- web/app/notifications.py
This pull should fix the issue where alerts would be muted and TSD would no longer monitor a print if EU clicks on the resume link.
Line 55 initially had mute_alert set to true. Removing that flag from the URL here does fix the issue at least after my testing.
> Fix E-Mail Notification link.

- web/app/notifications.py
To be able to trigger scripts based on failed prints, I added more meaningful output to the log when sending an alert, allowing it to be parsed based on failing/fishy prints.
> Added more meaningful alert status to stdout

- Makefile
- docker-compose.yml
- web/Dockerfile
- web/Dockerfile.base
Added make commands for building images. 
* `make build-web-base-1.2` builds the base web image.
* `make build-images` rebuilds all images with extra build-arg passed. Only `web` (and `tasks`) can use them right now. Default user in these containers is going to be `user` with uid and gid of actual host user at build time.
* `make build-web-and-tasks` will just (re)build those images.
If you simply use `docker-compose build` then nothing changes, you are going to have `root` as default user inside those containers. 
I did update make commands related to frontend as well. Both building/serving now reuses web container. No docker compose overrides etc is needed to make it work anymore.
* `make build-static` builds production bundles.
* `make frontdev-up` starts the hmr capable webpack dev …
> Run as "user" instead of "root" in web container

- web/app/tunnel.py
When tunnel page does not end in '/' then relative src url clears <printer_id> (last path segment).
> Url rewrite fixes for tunnel

- web/app/forms.py
- web/app/templates/account/login.html
- web/app/urls.py
- web/app/views/web_views.py
If user signs up using google/fb then no password is set for the account. This PR displays a warning when such user tries to login using email/password pair.
> Login form warning for social-account users without usable password

- web/app/static/js/printer_controls.js
- web/app/static/js/printer_ws.js
- web/app/static/js/webrtc_streaming.js
- web/frontend/src/common/StreamingBox.vue
- web/frontend/src/lib/event_bus.js
- web/frontend/src/lib/printer_ws.js
- web/frontend/src/lib/webrtc_streaming.js
Passthru messages might be sent/received over webrtc datachannel (as well) for faster delivery.
Plugin branch: https://github.com/TheSpaghettiDetective/OctoPrint-TheSpaghettiDetective/pull/105
Janus branch: https://github.com/encetamasb/janus-gateway/pull/1/files
I tried to change as less code as possible. This is why all datachannel messages are emitted/processed in ws connection managers.
When testing this PR using docker-compose make sure that both server and plugin projects run in the same (docker) network.
> Passthru messages over webrtc (webapp side)

- docs/jetson_guide.md
After a linked conversation on discord, i decided to add more resources on how to download docker-compose on a jetson nano. I also added a note on the download speed of JetPack SDK from the Nvidia website.
> Update the Jetson guide on Docker-compose installation

- web/app/views/tunnel_views.py
REDIRECT_URL has to be overridden in tunneled html
> Fixed tunnel login redirect

- web/lib/notifications.py
Added a variable called 'color' and defined it as green or red depending on if the print had been cancelled or not. Previously only the color red was being used.
> Make successful print messages green for discord

- docker-compose.yml
- web/config/settings.py
- web/lib/notifications.py
I'm running TSD self hosted behind a proxy that add a layer of authentication.
The actual notifications system detects my server as a public one (because it is exposed by a public url) and then add a link to the snapshot into the email. But because of the requested authentication the link into the email is broken.
This new setting allows to force snapshots to be attached to the notification email. It does not change the default behavior but add extra flexibility for self hosted environements.
I hope you'll find this feature interesting, feel free to change any name if you think there aren't clear enough.
> Adding a new setting to include snapshots into email

- web/app/tasks.py
- web/config/celery.py
Let workers have only 1 extra task (default is 4) in their local queue.
Let an unstarted app.tasks.compile_timelapse task be requeued (by adding acks_late=True) when worker is lost. 
(https://docs.celeryproject.org/en/4.4.1/userguide/optimizing.html?highlight=optimizing#prefetch-limits)
> Minimalize possibility of dropped celery tasks

- web/lib/mobile_notifications.py
Fixes an OverFlowError when value is unexpectedly a string, "*****".
> When print time left is invalid, let's not add it to the notification

- web/api/consumers.py
Strange bug, printer id can become None...
> Let's force reconnection when ws consumer state is corrupted

- web/api/octoprint_views.py
- web/api/serializers.py
- web/api/urls.py
- web/api/viewsets.py
Frontends need to be able to distinguish Http403 (here that means unauthenticated) and Http404 cases,
when polling for verification code state updates. This is the main reason of touching this code.
Verify endpoint has different authentication requirements, by separating it the code gets clearer and more standard.
Added proper validation error reporting code here and there; these may help in detection of - otherwise silent - problems.
> Use standard permission check flow in verification code viewset

- web/frontend/package.json
- web/frontend/src/lib/janus.js
- web/frontend/src/lib/webrtc.js
- web/frontend/yarn.lock
Starting from latest upstream janus.js, I tried to recreate an improved experience, with minimal code changes in janus.js itself.
* Ignoring janus messages targeting other instances (running in other devices/browsers)
* Close session when session is no longer present on janus server
* ipv6 is enabled client side
>  Fixes and improvements for Janus

- docker-compose.yml
- web/app/models.py
- web/app/templates/account/base.html
- web/app/templates/account/login.html
- web/app/templates/account/signup.html
- web/app/templates/new_octoprinttunnel.html
- web/app/templates/new_octoprinttunnel_succeeded.html
- web/app/urls.py
- web/app/views/tunnelv2_views.py
- web/frontend/src/printers/PrinterCard.vue
- web/lib/view_helpers.py
3rd-party app requested tunnel authorization by opening a page at:
`/tunnels/?app=app_name[&printer_id=printer_id]`
printer_id is optional.
Please review for security holes.
Also https://github.com/TheSpaghettiDetective/TheSpaghettiDetective/pull/525/files#diff-b63f8f471707ae81afb1d0d50f0b20804fddfe7286490bcfad01fcab54e1b6feR3 doesn't work as expected. Now both /accounts/login/ and /accounts/signup/ pages have no navbar even without `?hide_navbar=true` param. I'll appreciate it if you can help me figure this out.
> Create a new 3rd-party tunnel by request

- web/lib/tunnelv2.py
(1) Do not allow access for archived printers
(2) Return WWW-Authenticate header only for "integration" tunnels
> Fixes for tunnelv2

- web/config/settings.py
Default values for env vars in docker-compose.yaml are parsed differently in different docker-compose
versions. Working around that.
> More permissive logic when parsing bools from env

- web/app/middleware.py
- web/config/settings.py
Recent cookie domain change still causes problems in ios app.
Cleaning up the situation by changing the cookie name.
> Renamed django session cookie

- docs/model_development.md
Part of #552 - this includes instructions on how to build the model container, update the `*.so` files, and work around some troubleshooting errors. 
Doc reflects the current state of things - it'll need revisions when #552 changes aspects of how things are built/run.
> Added model_development.md

- docs/jetson_guide.md
- docs/unraid_guide.md
Not all users have their public keys set up on github.
`git clone git@github.com` will fail for many users, especially the ones who don't really use github.
> HTTPS should be used instead of SSH for git clone in the guides

- web/api/octoprint_views.py
- web/app/models.py
This is a companion PR to to https://github.com/TheSpaghettiDetective/OctoPrint-TheSpaghettiDetective/pull/158 that allows passing "tags" when sending octoprint commands. These are currently ignored by the OctoPrint TSD plugin, but can be used by other plugins to take action when TSD detects failures. 
It passes a `failure_detected` tag when TSD detects spaghetti. I intend to use this in https://github.com/smartin015/continuousprint to differentiate between when TSD pauses due to spaghetti and when it pauses via e.g. button click in the UI, with the former triggering a "clear bed and restart print" and the latter waiting for user input.  
**Why add a `tags` and not just extend `args`?** 
[The `args` field is spread](https://github.com/smartin015/OctoPrint-TheSpaghettiDetective/blob/2bfcf79 …
> Add tagging of octoprint commands

- README.md
this warning will serve to remind users that with our rapidly changing repo, they should always cross-check with the commands located here. This will help solve some issues users still following old guides are having.
> update readme with warning

- README.md
- website/docs/server-guides/configure.md
Updated the readme to include instructions on how to set up Bonjour/Avahi on all systems for easier server connection. Will write up a script intended for Jetson that will set up avahi automatically, and will prompt user if they want to set their hostname to `obico`
> Update README with Bonjour/Avahi Instructions

- README.md
- scripts/avahi_setup_jetson.sh
- scripts/install_on_jetson.sh
- website/docs/server-guides/configure.md
Added a script that installs and sets up Avahi on the Jetson at server setup. User can opt out.
Also improved configuration docs for linux as avahi needs some setup to be good.
Fixed broken link in readme to avahi setup.
> Avahi script for Jetson & Doc improvements

- backend/app/middleware.py
- backend/config/settings.py
- docker-compose.yml
When enabled, /admin/ is accessible only from ip-s whitelisted in django
settings.
ADMIN_IP_WHITELIST env var is expected to be a json list of ips, when
set (like '["1.2.3.4", "5.6.7.8"]').
> Admin site ip whitelist feature

- website/docs/server-guides/advanced/reverse-proxy.md
To keep consistency with the [email setup](https://www.obico.io/docs/server-guides/configure/#email-smtp) I think it would be better to set all parameters in the `.env` file instead of telling the user to modify `docker-compose.yml` (arguably more sensitive to errors)
> Modify .env instead of compose file

- backend/api/consumers.py
Removed one connect method override added by mistake, this fixes shared printers.
Added additional @close_on_error rule.
> Fixes for consumer error reporting

- backend/app/views/tunnelv2_views.py
Now octoprint requires csrf token as both cookie and header. Port in cookie name become an issue as tunnels might be accessible over a different port than expected.
https://github.com/OctoPrint/OctoPrint/commit/59a0c8e8d79e9d28c4a2dfbf4105f8dd580a8f04#diff-ca20d21b0455b1fc66bbb24d3b470d47a1ce5329ad2ab9918506d0ab95a9517fR175
> CSRF fix for octoprint 1.8.3

- backend/app/storage.py
- backend/config/settings.py
Original idea:
https://adamj.eu/tech/2022/01/26/django-and-source-maps/#backport-to-the-future
I made it to ignore exceptions of missing map files in post_process method.
> Fixed missing map files issue

- website/docs/user-guides/moonraker-obico/config.md
To match the config option in the dev branch of moonraker-obico, add references to target_fps in documentation
> Add target_fps to moonraker examples

- backend/notifications/tasks.py
Hi,
I noticed that I did not get failure notifications via pushover anymore and looked into that.
The reason I found was, that another active plugin threw an exception due to an invalid token. Any further plugins were not called anymore, including pushover in my case.
For the general notifications, all plugin exceptions are handled, but that's not the case for the more important failure notifications.
To mitigate the issue, I added the same kind of error handling for failure notification as for general notifications.
Cheers
> fix exception in notification plugin stopping further processing

- backend/config/settings.py
- docker-compose.yml
- dotenv.example
I had an issue using obico behind a cloudflare tunnel. Hence, CSRF_TRUSTED_ORIGINS must be set in the django config (https://docs.djangoproject.com/en/5.0/ref/settings/#csrf-trusted-origins). This PR adds an optional parameter to the .env to set theses trusted origins.
```
Forbidden (403)
CSRF verification failed. Request aborted.
Help
Reason given for failure:
Origin checking failed - https://obico.rasgi.de does not match any trusted origins.
In general, this can occur when there is a genuine Cross Site Request Forgery, or when [Django’s CSRF mechanism](https://docs.djangoproject.com/en/4.0/ref/csrf/) has not been used correctly. For POST forms, you need to ensure:
Your browser is accepting cookies.
The view function passes a request to the template’s …
```
> Add CSRF_TRUSTED_ORIGINS as optional environment variable

- ml_api/server.py
```text
21:50:49 kaszpir@lynx ~/Downloads $ curl -v "http://127.0.0.1:13333/p/?img=http://bagno.hldspl/obico/bad_1.jpg"
*   Trying 127.0.0.1:13333...
* Connected to 127.0.0.1 (127.0.0.1) port 13333 (#0)
> GET /p/?img=http://bagno.hldspl/obico/bad_1.jpg HTTP/1.1
> Host: 127.0.0.1:13333
> User-Agent: curl/7.81.0
> Accept: */*
> 
* Mark bundle as not supporting multiuse
< HTTP/1.1 503 SERVICE UNAVAILABLE
< Server: gunicorn
< Date: Fri, 16 Feb 2024 20:51:09 GMT
< Connection: keep-alive
< Content-Type: application/json
< Content-Length: 399
< 
{
"detections": [],
"message": "Failed to get image ImmutableMultiDict([('img', 'http://bagno.hldspl/obico/bad_1.jpg')]) - HTTPConnectionPool(host='bagno.hldspl', port=80): Max retries exceeded with url: /obico/bad_1.jpg (Caused by …
```
> Add better error messages to ml_api
