web/requirements.txt

Fixes the logging issue that we have been discussing.

Upgrade to django-request-logging 0.6.8

---

README.md

Not that useful, but makes it look a bit nicer

Fix spelling/grammar

---

web/app/templates/account/password_change.html
web/app/templates/includes/_printer_form.html
web/app/templates/includes/_secret_token.html
web/app/templates/layout.html
web/app/templates/printer_auth_token.html
web/app/templates/printer_list.html
web/app/templates/printer_wizard.html

This is an initial set of accessibility tweaks for #74, this isn't 100% accessible still as I haven't gone thru the non-automated audits, nor have I adjusted the colors as the background/foreground colors are too similar according to lighthouse.  This also includes one typo fix as well as pointing to minimized css and javascript for one of the libraries used since I noticed that as an easy win under the performance section.

Initial accessibility fixes for #74

---

web/requirements.txt

Downgrade pillow to avoid build errors

---

docs/nginx_config.md

Fixed websocket locations for NGINX Reverse Proxy

Fix websocket locations

---

docs/advanced_config.md
docs/faq.md
docs/nginx_config.md

Moved some things to more appropriate locations

Updated document formatting

---

web/app/telegram_bot.py

Request a new telegram connection every time instead of only when telegram_bot.py is first included. This avoids timeouts.

Request a new telegram connection every time.

---

web/app/telegram_bot.py
web/app/templates/user_preferences.html
web/app/urls.py
web/app/views.py

- new 'Test Telegram Notification' in user prefs
- reports error for telegram API startup issues rather than crash
- fixes #151 (Web startup loop from error)

More rugged telegram api startup, adds Test-Telegram button

---

Makefile
web/Dockerfile
web/Dockerfile.base

This way it's easy to reuse web image for frontdev during development. This change should not affect production.

Added with_node arg for building web image with node/yarn

---

web/frontend/.eslintrc.js
web/frontend/package.json

Downgraded vue level to essentials.

Separated eslint config into standalone file

---

web/frontend/src/main/main.js

Fixed module import style

---

web/frontend/package.json
web/frontend/src/print_shot_feedback/main.js
web/frontend/yarn.lock

Switched to vue-sweetalert2

---

web/frontend/vue.config.js

Instead of
import "../common/X"
one can use
import "common/X"

Added import aliases

---

web/frontend/src/common/Gauge.vue

Fixed gauge title and color

---

Makefile
docker-compose.yml
web/Dockerfile
web/Dockerfile.dev

Should fix #247 
Current docker version on Synology NAS systems is buggy and cannot properly handle build ARG-s.

Separated dev Dockerfile to fix compability issues

---

docs/unraid_guide.md

This is a simple guide to install TSD on unRAID. Sources for the commands used that are not mine or TSD's are cited as links inline in the guide.

Add Guide to install TSD on unRAID.

---

docs/unraid_guide.md

Added CPU limiting instructions, and made the general setup and configuration sections more detailed.

Updated unraid_guide.md with CPU limiting

---

README.md

Just fixes a some spelling errors I noticed while reading through the README

Fix minor spelling errors in Readme

---

web/app/accounts.py
web/config/settings.py

At social signup do not try to create new account if email has been registered already

Merge social signup into existing email-registered user

---

web/app/forms.py
web/app/migrations/0047_user_pushover_tokens.py
web/app/models.py
web/app/templates/user_preferences.html
web/lib/integrations/pushover.py
web/lib/notifications.py

Added basic integration of Pushover API.

Added pushover integration as per #90

---

docs/jetson_guide.md

Added how to install pip and how to install docker-compose through pip3. Also changed the docker-compose instructions to creating a new docker-compose override file to facilitate updates to the code better.

Added more installation information to Jetson-guide.md

---

docs/jetson_guide.md

Removed an extra line that was accidentally added in the previous commit.

Removed an extra line

---

docs/jetson_guide.md

Thanks to a script i wrote with some help from @Ryryog25#3776, I was able to write a script to reliably install docker compose with pipenv. I re-wrote the guide to include usage of this script.

Rewrote guide to include pre-req script.

---

docs/faq.md

I changed the secret token test to "Server Connection Test" to reflect recent TSD, as well as changed the error message to reflect the new one.

Just updated some simple wording, etc.

---

web/app/views/tunnel_views.py
web/lib/cache.py

Let's not pull **static assets** through tunnel if requested `ETag` matches
last seen version. In these cases server can immediately respond with
a `HTTP 304`.

ETag cache for faster tunneling

---

web/frontend/src/lib/janus.js

https://github.com/meetecho/janus-gateway/commit/4f0f95bd13d277f45689291cd7682d58d84996dd

Hotfix for janus.js: null protect invalid PeerConnection

---

docs/jetson_guide.md

Fix typo in jetson_guide.md

---

web/app/forms.py
web/app/templates/account/signup.html

While reported errors might be result of malicious bot activity, let's make sure that a innocent human can see a more actionable error message.

Validation error instead of unhandled exeception in case of reCaptcha problems on signup form

---

web/api/printer_discovery.py

Reverts TheSpaghettiDetective/TheSpaghettiDetective#487

Revert "Added ip/port and machine_type to device info (printer discovery)"

---

web/lib/mobile_notifications.py

Smaller payload size might fix rare "InvalidArgumentError" issue.

[firebase] Skip arguments meant for other platforms

---

Makefile
web/Dockerfile
web/Dockerfile.base
web/Dockerfile.dev
web/requirements.txt

We can save some bandwidth etc, when it's in use.
It needs the base image to be rebuilt. Let's merge only when we prepare next one.

[NEEDS NEW BASE] Added brotli support for whitenoise

---

web/api/consumers.py

As that may leak information owner might not want to share.

Disabled datachannel for shared printer connections

---

web/app/models.py
web/app/templates/new_octoprinttunnel.html
web/app/views/tunnelv2_views.py
web/lib/tunnelv2.py

(1) Let's store only hash of basicauth password
(2) Minimal cleanup of provided app_name
(3) Moved POST endpoint into semi-separate function, with explicit @login_required
(4) Fixed typo in returned tunnel url param name

Updates for new app tunnel

---

README.md

User UNSCSpartan3 on Discord requested that these two items be added to the private server README.md. I have added these in to the best of my abilities. Please alter them how you see fit. I do feel like this information (as well as a lot more) could be useful to have on this guide.

Added app config and Timelapse location

---

README.md

Upgrade instructions were Linux only, so I updated them for any OS.

Update Upgrade instructions

---

README.md
docs/email_guide.md

Changed readme to show the correct version of docker compose needed
Updated a few pieces of info for the email troubleshooting doc along with some formatting/wording changes

Update Readme and Email Troubleshooting

---

backend/app/views/web_views.py
frontend/src/views/printer-wizard/PrinterWizardPage.vue
frontend/src/views/printer-wizard/wizard-routes.js

Fixed issue: if you select platform and url changed to `.../wizard/setup/` after page refresh there will be 404 error

Fix wizard issue

---

docs/model_training.md

This guide is mostly speculative - don't merge this PR. #589
I haven't yet done the legwork to train any models yet. I wanted you to see it early to let me know if there's anything you'd like to change before I actually start writing scripts and running code. 
A couple specific things I'd like feedback on:
* If you'd prefer I embed example code for running commands (vs checking in a script) let me know and I'll adjust.
* I cautioned folks from contributing fine-tuned models for their particular environment. Would you rather this, or that they open a pull request so you can see what they did?
* Do you have any guidance on a reasonable learning rate for fine tuning? 0.0005 was a stab in the dark.

Model refinement doc

---

website/docs/user-guides/octoprint-plugin-setup-manual-link.md

Under `## Step 6`, corrected "shinny" to "shiny".

"shinny" typo

---

backend/notifications/plugins/webhook/__init__.py
frontend/src/notifications/plugins.js
frontend/src/notifications/plugins/WebhookPlugin.vue
frontend/src/notifications/plugins/webhook.vue

Adds Webhook Notification Plugin. All event types tested and confirmed working.

Adds Webhook Notification Plugin

---

frontend/src/components/StreamingBox.vue

Clarifying error message through slight wording change / cleanup.

Fix grammatical error and phrasing

---

README.md
docs/model_development.md
docs/model_training.md
website/docs/server-guides/advanced/nginx-proxy-manager.md
website/docs/server-guides/advanced/nvidia-gpu.md
website/docs/server-guides/advanced/reverse-proxy.md
website/docs/server-guides/hardware-requirements.md
website/docs/server-guides/index.md
website/docs/server-guides/install.md
website/docs/server-guides/platform-specific/unraid_guide.md
website/docs/user-guides/enable-gcode-thumbnails.md
website/docs/user-guides/first_layer_ai/nozzle-camera-configuration.md
website/docs/user-guides/first_layer_ai/slicer-configuration-for-first-layer-ai-klipper-only.md
website/docs/user-guides/help-the-detective-improve.md
website/docs/user-guides/orange-pi-for-octoprint-download-setup.md

Addressed some spelling mistakes
Fixed capitalization of some company/product names
My VSCode settings removes trailing spaces by default, so may have some of that sprinkled in

Spelling corrections

---

backend/notifications/plugins/email/__init__.py

Fix email image attachments

---

backend/notifications/plugins/email/__init__.py

Fixes multiple email attachments as described in comments of [#822](https://github.com/TheSpaghettiDetective/obico-server/issues/822#issuecomment-1745879328)

fix mutable default

---

backend/api/viewsets.py
backend/app/urls.py
backend/app/views/fs_media/urls.py
backend/app/views/fs_media/views.py
backend/app/views/web_views.py
backend/lib/utils.py

Enforces authc/authz checks for media files

Secure media view

---

.github/workflows/build-images.yaml
ml_api/Dockerfile.base_amd64

Adding Docker Build Actions
Adds GitHub Actions to Build Images and store them in the GitHub Container Registry

Adding Docker Build Actions

---

backend/api/urls.py
backend/api/viewsets.py
backend/config/settings.py
frontend/src/components/user-preferences/ApiKey.vue
frontend/src/config/server-urls.js
frontend/src/config/user-preferences/routes.js
frontend/src/config/user-preferences/sections.js

Just hacking together something what works. 
It's using TokenAuthentication from restframework.
https://www.django-rest-framework.org/api-guide/authentication/#generating-tokens

Added endpoints and minimal frontend for orcaslicer integration

---

website/docs/server-guides/configure.md

the email config example made no mention to remove the # symbol

Update configure.md email example

---

website/docs/user-guides/klipper-setup.md

Elaborates on the config file locations for Klipper and Moonraker, adds clarification on what Klipper with Moonraker is supposed to mean, and slightly improves the flow of the Klipper install.sh bash script steps.

Update klipper-setup with elaboration on configs

---

website/docs/server-guides/advanced/reverse-proxy.md

Update documentation for [#876](https://github.com/TheSpaghettiDetective/obico-server/pull/876)
Since I am not a native English speaker, someone else shlould take a look on spell and grammar.

Update documentation for PR #876

---

frontend/package.json
frontend/src/components/HelpWidget.vue
frontend/src/components/StreamingBox.vue
frontend/src/components/SyndicateAwareLogo.vue
frontend/src/components/print-shot-feedback/FocusedFeedbackConsent.vue
frontend/src/components/printer-control/PrintJobControlWidget.vue
frontend/src/components/printers/AutoLinkPopup.vue
frontend/src/components/printers/SharePrinter.vue
frontend/src/components/prints/PrintCard.vue
frontend/src/i18n/base/en.json
frontend/src/i18n/i18n.js
frontend/src/i18n/yumi/en.json
frontend/src/mount.js
frontend/src/notifications/plugins/SlackPlugin.vue
frontend/src/notifications/plugins/TelegramPlugin.vue
frontend/src/views/GCodeFoldersPage.vue
frontend/src/views/NewOctoPrintTunnelPage.vue
frontend/src/views/OctoPrintTunnelPage.vue
frontend/src/views/PrintPage.vue
frontend/src/views/PrinterControlPage.vue
frontend/src/views/PrinterSettingsPage.vue
frontend/src/views/SharedPrinterPage.vue
frontend/src/views/UploadPrintPage.vue
frontend/src/views/printer-wizard/PrinterWizardPage.vue
frontend/yarn.lock

what did i do:
1. Add i18next and i18next-vue dependencies to the obico-server/frontend warehouse
2. Add i18n configuration in the obico-server/frontend/src/i18n folder
3. Add integration code in obico-server/frontend/src/mount.js
4. Replace all Obico with {{$t('name')}} or ${this.$t('name')}

feat: i18n-obico-yumi

---

backend/app/tasks.py

Enabled timelapse detection email for base

---

website/docs/user-guides/enable-gcode-thumbnails.md

Fixed a slight spelling mistake in step 5 of the instructions for Cura 4.9+

Update enable-gcode-thumbnails.md to fix slight spelling mistake.

---

docker-compose.yml
website/docs/server-guides/install.md
website/docs/server-guides/ops.md

Hi,
correction/improvement of [PR 1046](https://github.com/TheSpaghettiDetective/obico-server/pull/1046)
br,

Add healthchecks to docker-compose.yaml
